services:
  frontend:
    build:
      context: ../VolvoFrontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Volvo.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=mydb;User Id=sa;Password=YourPassword123;Encrypt=False;

    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql_data:/var/opt/mssql

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
